system:
  timing_interval: 1

  video_source: "file"
  video_sources:
    file:
      filename: "../test_clips/步兵素材蓝车侧面-ev-0.MOV"
    camera:
      id: 0
      width: 640
      height: 360
      fps: 330

  video_target: "dummy"
  video_targets:
    dummy: "dummy"
    file:
      folder: "record"
      segment_interval: 30
    webserver:
      port: 2019
  
  target_calibration:
    view_angle_x: 45          # 摄像头左右能拍到的最大角度
    view_angle_y: 45          # 摄像头上下能拍到的最大角度
  
  serial:
    device: "/dev/ttyS0"
    baudrate: 115200

game:
  our_team: "red"

algorithm:
  icra2018_njust_armor:
    min_light_gray: 210
    min_light_height: 8
    avg_contrast_threshold: 110
    light_slope_offset: 30
    max_light_delta_h: 500
    min_light_delta_h: 35
    max_light_delta_v: 40
    max_light_delta_angle: 30
    avg_board_gray_threshold: 100
    avg_board_grad_threshold: 25
    grad_threshold: 25
    br_threshold: 30
    template_image_file: "src/algo/icra2018_njust_armor/template/template.bmp"
    small_template_image_file: "src/algo/icra2018_njust_armor/template/small_template.bmp"
